// <auto-generated />
namespace Supeng.Examination.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class examinationquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(examinationquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201606300825487_examination-question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
