// <auto-generated />
namespace Supeng.Examination.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userexamination3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userexamination3));
        
        string IMigrationMetadata.Id
        {
            get { return "201607010758055_user-examination-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
