//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supeng.Weixin.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supeng.Weixin.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={0}&amp;corpsecret={1}.
        /// </summary>
        internal static string ConnectUrl {
            get {
                return ResourceManager.GetString("ConnectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token={0}.
        /// </summary>
        internal static string CreateUserUrl {
            get {
                return ResourceManager.GetString("CreateUserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/user/delete?access_token={0}&amp;userid={1}.
        /// </summary>
        internal static string DeleteUserUrl {
            get {
                return ResourceManager.GetString("DeleteUserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/user/simplelist?access_token={0}&amp;department_id={1}&amp;fetch_child={2}&amp;status={3}.
        /// </summary>
        internal static string GetUserListUrl {
            get {
                return ResourceManager.GetString("GetUserListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={0}.
        /// </summary>
        internal static string SendMessageUrl {
            get {
                return ResourceManager.GetString("SendMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://qyapi.weixin.qq.com/cgi-bin/user/update?access_token={0}.
        /// </summary>
        internal static string UpdateUserUrl {
            get {
                return ResourceManager.GetString("UpdateUserUrl", resourceCulture);
            }
        }
    }
}
